### ISSUE TITLE
specification: #cpus-mask-cells is undefined

### ISSUE THREAD

**Issue by mbolivar-nordic** [devicetree-org/lopper#133]
This property appears in system-device-tree.dts and source/chapter5-bus-firewalls.rst, but its semantics are undefined.

**Comment by mbolivar-nordic** [comment]
cc @sstabellini . Just another one I found while writing up the bindings for CPU clusters.

**Comment by sstabellini** [comment]
Hi @mbolivar-nordic , I think that is a mistake and should be removed. It looks like #cpus-mask-cells is the same as #ranges-address-cells, so it is redundant
