### ISSUE TITLE
Support for OpenAMP YAML Overlays has regressed

### ISSUE THREAD

**Issue by bentheredonethat** [devicetree-org/lopper#183]
Unable to use OpenAMP 

I am using lopper-demo inputs and this is failing

bash script below:

LOPPER=lopper
OVERLAY=opper/demos/openamp/inputs/openamp-overlay-zynqmp.yaml
LOPS_DIR=${LOPPER}/lopper/lops
SDT=lopper/demos/openamp/inputs/system-dt/system-top.dts

python3 ${LOPPER}/lopper/__main__.py -f  --enhanced  --permissive \
        -i ${OVERLAY} \
        -i ${LOPS_DIR}/lop-load.dts \
        -i ${LOPS_DIR}/lop-xlate-yaml.dts \
        -i ${LOPS_DIR}/lop-openamp-versal.dts \
        -O . \
        ${SDT} \
        openamp_output.dts

The domains YAML is not applied properly.
error output:
[WARNING]: assist <function openamp_parse at 0x7f302b1f9430> failed: '/domains'
<class 'KeyError'> __init__.py 1442

CC @zeddii

**Comment by bentheredonethat** [comment]
I believe this commit 
b548dae3a652d3e3d44b4372339995426c8a0b57 

introduces the error

**Comment by zeddii** [comment]
Right, if it isn't DTS, it isn't being merged into the main device tree anymore, since we need to be able to handle specifications and other associated information passed to processing.

I'll see about making an exception for yaml, so it can be expanded and merged as it used to be.

**Comment by bentheredonethat** [comment]
Ok thanks for the quick response!
